### ISSUE TITLE
RQ-802 폴더 삭제

### ISSUE THREAD

**Issue by SeoHong23** [greenlotte4/lotte-2nd-project-front-team2#138]
드라이브 폴더 삭제 기능을 구현한다.
- 삭제된 폴더는 휴지통 보관
- 휴지통에 보관 중인 폴더 복구 기능

**Comment by jin123346** [comment]
삭제된 폴더는 휴지통 보관

**Comment by jin123346** [comment]
삭제된 폴더는 휴지통 보관
휴지통에 보관 중인 폴더 복구 기능
